language: node_js

node_js:
  - "6.14.1"

env:
  - VERSIE="versie 6"

before_install:
  - echo "before install versie = $VERSIE" 

install:
  - npm install

script: 
  - echo "script versie = $DUMMY" 
  - npm test
