language: node_js

node_js:
  - "6.14.1"

env:
  - global:
    - VERSIE="versie 6"
    - secure: "yurgfP51N/GrAtDZDebn5jmgcaiVe2CT4TCqwdHMCJF4fdzTA1rB7cTJqcC0uPUXJN6FHKmoBBpQxZpD8G3Mi/8LSVfI0mToHEjroxS+n6TOf/+GND6VMPVyaH54p4Hec3g1k25lD72j+Qokc7NVo2odRwBsQ4lQ6qjEJgT00MehppKIFg1vKNAkCseFB1IpjJJXzpV6KkzzbSR5Ao5N1pU1WMu7JU6q5v0Io0mR6TiClMxvhQv1BfW6XcqQkInhpU/JeHLfePAGhMsrgmonh0O5OIK2ZlraHuQBq2Jo0XrgsVQcbjTiwlVuUSkF96Pg8dmRlEWPL4xsHmWUwxvzGz10I1Jl6WWucMNaIXkbBMu+PF9u6d8VMe7Ixz/S0GIbuyMB/Me5MS3SFXsOGiMIiNYHB6+bz8mACj7lgZKlB8KP49pE+EeIelK92y7Myi3kNUr+b0VYrq3aw17SPuhtI+RxHAvMywloSDDzSXuUJ7JJWJRKo/IG6dVUH6NCCPlMA2C7qgm8W0l/pqdMy2yIL1qpMXyotB7lHPedSc5aWle7VW97W9ttxrqkH82JsfVvhdxMx4u0XqTxMD6nQquBF1xGP7fRsYXYhvut/pOQxZmndHXgVGKHR52c8TqBrSaQYDg7/pMjlV2j1yWgOCDpY7ai25R/lTYGgSTp9NXoDik="
    - secure: "VGyP1bs5kJaR2jL5lQbcQ6gLYp3uJhqs2rvfR0bwNZplRgEuJ6WfL+U4gu6fzZE2j5bTOeE3v7EIDA8yJVAASdd1uTI5bO3iDRtWXnhANP2ggOK2F+TeqtBEZb+zOipm/gC0tU4DfnvqrYWJ4f5dVKK4BQcxoV6ubzLdtfhIfICvogPZqt/3bQWm0grtHoGo5d7Yjrk2oULNiZ/Uef+D0LgddAZROlFMX6A7BdthdEiuMSVzjjkZbXK0vdGBV51jYXM4yh27c41QMbbSIUDtYOGV1lqocEZY2r7huqzGaotD04Ti9isbtPRvmGaekFvl6+0l54sDXPNSAUAJpl2rdf3kf8TOhs3851JbPz+PygW4pgOjwPJYyjkShIqH7qvZrYAtBWE8nt1MOD1p5GSKLtVThvg9AcbN5+oaBxMmxmnXRslbz6Cn/X1JkniG6/JKsq+FLdqHJXkWHhTYB8QB8Er3A0J59AWdv2OCMBXQifs7JZyUQEm5++cfBsDL9nF+xtopn2+nUMtty2g5n3sosIFhHJKgXrSiMxXZBUCVqlInhUbfgVTe+HO+jQSirZ3pv7Y5wYU962b8fliuExeSMem8xjsPa2V8BcuCmka6+gtWixcb28UuQqkEsftd2pTKb365zIxV9QDuuRtlqoLCasFI82BLjbGd38LKpGKevjg="

    before_install:
  - echo "before install versie = $VERSIE" 

install:
  - npm install

script: 
  - echo "script versie = $VERSIE" 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAM" --password-stdin
  - npm test
